# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'WearTime' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for WearTime


  pod 'Masonry'
  pod 'AFNetworking'
  pod 'WechatOpenSDK'
  pod 'QMUIKit'
  pod 'YYCategories'
  pod 'SVProgressHUD'
  pod 'BEMCheckBox', '~> 1.4.1'
  pod 'LookinServer' , :configurations => ['Debug']
  
  
  pod 'JCore'
  pod 'JPush'
  pod 'JVerification'
  pod 'JShare'
  
  pod 'WechatOpenSDK'
  
  pod 'IQKeyboardManager'
#pod 'UMCommon'
#pod 'UMDevice'
#pod 'UMShare/UI'
#pod 'UMShare/Social/WeChat'

end
